commit_message: '[ci skip] New %language% translation from Crowdin'
append_commit_message: false
files:
  - source: /jupyterlab/locale/jupyterlab.pot
    translation: /jupyterlab/locale/%locale_with_underscore%/LC_MESSAGES/%file_name%.po
  # Example for extensions
  - source: /extensions/jupyterlab-git/locale/jupyterlab_git.pot
    translation: /extensions/jupyterlab-git/locale/%locale_with_underscore%/LC_MESSAGES/%file_name%.po
