append_commit_message: false
commit_message: '[ci skip] New %language% translation from Crowdin'
files:
- source: /jupyterlab/locale/jupyterab.pot
  traslation: /jupyterlab/locale/%locale_with_underscore%/LC_MESSAGES/%file_name%.po
- source: /extensions/dask-labextension/locale/dask_labextension.pot
  translation: /extensions/dask-labextension/locale/%locale_with_underscore%/LC_MESSAGES/%file_name%.po
- source: /extensions/jupyterlab-git/locale/jupyterlab_git.pot
  translation: /extensions/jupyterlab-git/locale/%locale_with_underscore%/LC_MESSAGES/%file_name%.po
