name: Create Release and publish packages

on:
  push:
    tags:
    # Tags in the form, es-ES-vmajor.minor.patch
    - '[a-z][a-z]-[A-Z][A-Z]-v**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    env:
      CURRENT_TAG: ${{ github.ref }}
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade -r requirements/release.txt
    - name: Build release artefacts
      run: |
        export CURRENT_LOCALE_DIR=`python scripts/parse_release.py`
        echo ::set-env name=CURRENT_LOCALE_DIR::$CURRENT_LOCALE_DIR
        cd $CURRENT_LOCALE_DIR
        ls
        check-manifest -v
        python setup.py sdist bdist_wheel
        python -m twine check dist/*
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: true
        prerelease: false
        artifacts: ${{ env.CURRENT_LOCALE_DIR }}/dist/*
    - name: Publish PyPI Package
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        cd $CURRENT_LOCALE_DIR
        ls
        python -m twine upload dist/*
